#!/bin/sh
#
# Set up Java developer programs.

set -ex

echo 'Set up developer programs'
pkg install -y editors/vim devel/git

echo 'Set up sh developer programs'
pkg install -y devel/shfmt devel/hs-ShellCheck

echo 'Set up HTML/CSS/TypeScript developer programs'
pkg install -y www/node22 www/npm-node22
npm install -g corepack@latest
corepack install -g npm yarn pnpm

echo 'Set up Java developer programs'
pkg install -y java/openjdk21
echo -e 'fdesc\t\t/dev/fd\t\tfdescfs\trw\t0\t0' >> /etc/fstab
echo -e 'proc\t\t/proc\t\tprocfs\trw\t0\t0' >> /etc/fstab
mount -a
pkg install -y devel/maven
cp google-java-format.jar /usr/local/lib/
cp google-java-format /usr/local/bin/
chmod +x /usr/local/bin/google-java-format
