#!/bin/sh
#
# Set up MinIO.

set -eux

echo 'MINIO_ROOT_PASSWORD: '$MINIO_ROOT_PASSWORD
pkg install -y www/minio
sysrc minio_root_password=$MINIO_ROOT_PASSWORD
sysrc minio_enable=YES
service minio start
