#!/bin/sh
#
# Set up MinIO.

set -eux

echo 'MINIO_DISKS: '$MINIO_DISKS
echo 'MINIO_ROOT_PASSWORD: '$MINIO_ROOT_PASSWORD

pkg install -y www/minio
mkdir -p /usr/local/etc/minio/certs/
sysrc minio_enable=YES
sysrc minio_disks=$MINIO_DISKS
sysrc minio_console_address=":9001"
sysrc minio_root_user=minioadmin
sysrc minio_root_password=$MINIO_ROOT_PASSWORD
sysrc minio_syslog_enable=NO
service minio start
